# <ai_context>
# Docker Compose configuration for running the backend.
# Adjust ports and commands as needed for your environment.
# </ai_context>

version: "3.9"
services:
  backend:
    build: ./backend
    container_name: polymarket_backend
    volumes:
      - ./backend:/app
    ports:
      - "3001:8000"
    env_file:
      - .env
    command: ["python", "main.py"]
